### ISSUE TITLE
Empty password field shows "too short" rather showing "none or empty"

### ISSUE THREAD

**Issue by tombstone-10** [lannex/react-password-strength-bar#58]
Even when the field is empty, the bar says too short whereas it should show empty or none, i tried setting that by scoreWords and setting minLength but did not work. Is there a built in functionality for that?

**Comment by zyangchye** [comment]
Having the same issue here. I reckon this is because of this line of code?
https://github.com/lannex/react-password-strength-bar/blob/6371331f467099b120daf41de6510e5ca1d1054c/lib/index.tsx#L122

I would love to suggest if we could do something like

`(password.length && password.length >= minLength) ? scoreWords[score] : shortScoreWord;` instead

**Comment by palespectre** [comment]
You could store the value of the shortScoreWord in a state, and update it if the password is empty.

`
const [shortScoreWord, setShortScoreWord] = useState('');

const handlePassword = (value) => {
  setShortScoreWord(value === '' ? 'Field is empty' : 'Too short');
}
`

And then :
`
<input type="password" onCHange={(e) => handlePassword(e.currentTarget.value} />
<PasswordStrengthBar shortScoreWord={shortScoreWord} />
`

**Comment by tombstone-10** [comment]
That is a great approach, perhaps they can add it in the original code or make some function for it. Tried but did not work for me, anyways thank you!
